[package]
name = "cache-preloader"
version = "0.1.0"
edition = "2021"

[dependencies]
http-cache-reqwest = "0.16.0"
reqwest.workspace = true
reqwest-middleware = "0.4.2"
tokio.workspace = true

anyhow.workspace = true
clap.workspace = true
tar = "0.4"
flate2 = "1.0"
